### ISSUE TITLE
Error message in log file

### ISSUE THREAD

**Issue by antgrc87** [arc-lasalle/Map-On#1]
Hi, 
i followed the guide [https://github.com/arc-lasalle/Map-On/blob/master/docs/installation.md](url), all right until I put a scheme in a new datasource. In the mapping interface i can not see the columns of my test table.
In log file i have this message: 

> Query error: Field 'layoutX' doesn't have a default value - Invalid query: INSERT INTO `sourcetable` (`name`, `description`, `datasource_id`) VALUES ('TEST', '', 6)

The schema is created with the tool MapSchemaV0.2 and i have tested with success your demo version of Map-On. 
In MySQL the tables 'datasource' and 'sourcecolumn' have the right values. Can you help me to understand the problem?

**Comment by asicilia** [comment]
Could you share with ud the schema that are you using?

**Comment by antgrc87** [comment]
I have found the solution, there was a problem in MySQL. I tried to create another db and it works. Thank you for the answer.
